# Generated by Django 3.2.20 on 2023-09-08 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodolistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default=' nothing', max_length=120)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=120)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
